language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before-install:
    - sudo apt-get -qq update
    - sudo apt-get install -y tesseract-ocr ghostscript imagemagick
install: 
    - "pip install -r requirements.txt"
    - "pip install pytest mock"
    - "pip install ."
script: 
    - "pytest test"
